version: '3'
services:
  helidon-app:
    build: .
    ports:
      - "7001:7001"
  authors-service:
    container_name: authors-service
    image: app-authors
    ports:
      - 7001:7001
    links:
      - helidon-app

  books-service:
    container_name: books-service
    image: app-books
    environment:
      APP_AUTHORS_URL: http://authors-service:8080
    ports:
      - 7001:7001
    links:
      - helidon-app


  gateway-service:
    container_name: gateway-service
    image: app-gateway

    ports:
      - 9090:9090
    links:
      - helidon-app